# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  raylib_config = debug_x64
  rayterm_config = debug_x64
  yoga_config = debug_x64

else ifeq ($(config),debug_x86)
  raylib_config = debug_x86
  rayterm_config = debug_x86
  yoga_config = debug_x86

else ifeq ($(config),debug_arm64)
  raylib_config = debug_arm64
  rayterm_config = debug_arm64
  yoga_config = debug_arm64

else ifeq ($(config),release_x64)
  raylib_config = release_x64
  rayterm_config = release_x64
  yoga_config = release_x64

else ifeq ($(config),release_x86)
  raylib_config = release_x86
  rayterm_config = release_x86
  yoga_config = release_x86

else ifeq ($(config),release_arm64)
  raylib_config = release_arm64
  rayterm_config = release_arm64
  yoga_config = release_arm64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := raylib rayterm yoga

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C _build -f raylib.make config=$(raylib_config)
endif

rayterm: raylib yoga
ifneq (,$(rayterm_config))
	@echo "==== Building rayterm ($(rayterm_config)) ===="
	@${MAKE} --no-print-directory -C _build -f rayterm.make config=$(rayterm_config)
endif

yoga:
ifneq (,$(yoga_config))
	@echo "==== Building yoga ($(yoga_config)) ===="
	@${MAKE} --no-print-directory -C _build -f yoga.make config=$(yoga_config)
endif

clean:
	@${MAKE} --no-print-directory -C _build -f raylib.make clean
	@${MAKE} --no-print-directory -C _build -f rayterm.make clean
	@${MAKE} --no-print-directory -C _build -f yoga.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  debug_arm64"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo "  release_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raylib"
	@echo "   rayterm"
	@echo "   yoga"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"